### ISSUE TITLE
add JSON-LD export

### ISSUE THREAD

**Issue by odanoburu** [own-pt/mill#44]
this would help eliminate a python dependency and an export backend (since we'd get the RDF by joining the JSON output + with the json-ld context)

this would probably require a flattening of the relations in the synset document -- having each of them in the top-level instead of under the relations key. senses would be embedded in the synset (as now).

(we could use https://github.com/digitalbazaar/pyld for processing when needed, but this wouldn't be an actual dependency)

**Comment by odanoburu** [comment]
after discussing it with @hmuniz , we've decided to add a JSON-LD export backend which encodes relations as embedded documents inside the synset (as senses are embedded documents in the synset). see https://www.youtube.com/watch?v=UmvWk_TQ30A for a JSON-LD primer.

in RDF terms, this means there's a blank node between every two related {synsets, senses}, which stores which identifying relation and lexical form that was used for disambiguating the target sense in the text files (if any).

the public RDF releases will not have these blank nodes, of course.

**Comment by arademaker** [comment]
If I understood it right, something similar to what we did with the nominalizations in the past.

**Comment by odanoburu** [comment]
we have given up on JSON-LD given that no tools that we tested (jsonld.js, rdfpro) where able to handle the generated file (see https://github.com/dkmfbk/rdfpro/issues/12), and some were undocumented or underdocumented (pyLD)
